### ISSUE TITLE
Discuss whether to: Run (approved subset of) specification-tests against various servers

### ISSUE THREAD

**Issue by michielbdejong** [solid/test-suite#142]
We should run the [specification-tests](https://github.com/solid-contrib/specification-tests) against:
* NSS
* PSS
* Solid-Nextcloud
* CSS [runs them in CD/CI](https://github.com/CommunitySolidServer/CommunitySolidServer/blob/main/.github/workflows/schedule.yml)
* TrinPod
* pod.inrupt.com -> see https://gitter.im/solid/test-suite?at=61fa633b0779373db8c4c7e9

And add the results into the table.

**Comment by michielbdejong** [comment]
It wasn't clear to me [in the meeting on Monday](https://github.com/solid/test-suite-panel/blame/main/meetings/2022-05-09.md#L149-L150) whether all tests in https://github.com/solid-contrib/specification-tests have already been approved by the spec editors team, I know they went to a stricter review process than the jest-based tests, but I seem to remember @csarven saying they are currently *not* (all) approved, so maybe the set of approved tests is still empty now?

**Comment by edwardsph** [comment]
Please **do not** publish results from the specification-tests for any servers without permission from the implementers. I have made a public commitment to that effect on a number of occasions in blog posts and at SolidWorld. I made it clear to people that I didn't feel the specs or tests were ready for that. In time, it may be appropriate to publish results, or provide a platform for implementers to publish their results, but for now I committed to two things:
* If I ran the tests, I would make results available to the implementers via private channels.
* I would help any implementers to run the test harness themselves in order for them to get their own reports.

With regards to review status of tests, unfortunately I had to leave the meeting before that was asked. Some tests have been approved by editors, others are not yet reviewed. The status is shown in the reports and defined in the test manifests:
* https://github.com/solid-contrib/specification-tests/blob/main/protocol/solid-protocol-test-manifest.ttl
* https://github.com/solid-contrib/specification-tests/blob/main/web-access-control/web-access-control-test-manifest.ttl

There is a `--status` switch available in the test harness to enable it to only run approved tests though in practice people are running all the tests since even unreviewed tests can provide valuable insights and an opportunity to query the test designs. This could, of course, lead to noise if people keep seeing failing tests so where there are known issues or debates the intent is to capture these so that they also get included in the reports. An example of this is here: https://github.com/solid-contrib/specification-tests/blob/main/protocol/requirement-comments.ttl

There is also an opportunity for server developers to add notes about their implementations and to skip inapplicable aspects of tests (preferably with comments on why) here: https://github.com/solid-contrib/specification-tests/blob/main/test-subjects.ttl. The reports show cases like this by marking tests as inapplicable or untested using the EARL vocab.

There is a proposed process for contributing tests and getting them reviewed here: https://github.com/solid-contrib/specification-tests/blob/main/CONTRIBUTING.md

I suggest we close this issue but if an implementer still wants us to publish results, open a separate issue/PR in those specific cases.
Is that ok?

**Comment by michielbdejong** [comment]
Thanks @edwardsph 
That answers the question about which tests are approved and also makes it clear we don't agree on this as a task, so let's turn it into a discussion item. I'll change the title to that effect and let's find time to address it (whether in tomorrow's meeting or elsewhere), and we'll work together to find a way forward with this disagreement.

**Comment by michielbdejong** [comment]
After discussing with Pete just now I'm withdrawing this proposal.
We can use the specification-tests to find gaps in the jest-based tests, but then if we do find a gap, we can just add a jest-based test there. That way, the reports on solidservers.org are only about the output of the jest-based tests.

In the long run, the goal is for the jest-based tests to be fully replaced by the specification-tests, and for solidservers.org to be fully replaced by information published on solidproject.org.
