### ISSUE TITLE
Concerns about RDF-based approach to test writing

### ISSUE THREAD

**Issue by michielbdejong** [solid/test-suite#17]
I can quickly write tests like https://github.com/solid/test-suite/blob/master/testers/websockets-pubsub/tester/test/surface/change-events.test.ts and it would take me a bit longer to write the same test in Java or C++, but I know it's just a matter of writing the code to set up the conditions, execute some action (which may involve complex operations like generating a random cryptographic token or closing a WebSocket that was previously open, etc), and test assumptions about the results.

I can see how we could put references to test name, fixtures that go into a POST or PATCH body, and simple hard-coded values for things like http verbs and header values into RDF, and also how we could use RDF to specify the desired result, in case it's about the http response status etc.

But I fail to see how we could rewrite a test like the one I mentioned from JavaScript to RDF, nor why we would want to try to do that.

**Comment by kjetilk** [comment]
Firstly, RDF-based tests are not my idea, but what I see in test writing is that it ends up rather random abstractions or a lot of arbitrary cutnpaste. To tighten up this is attractive, I think.

Now, with the approach that I've taken, the parameters _are_ a part of the RDF description, and the actual tests themselves are encoded in reusable components. There should be very little overlap between them once dust has settled.

There is some appeal to the approach that I've taken in that it separates the implementation of a test from the description and parameterization of it.

I too think this approach has limitations, in particular, when you enter with a lot of logic, you'd likely do with tests that tries to explore for potential flaws that may create vulnerabilities. 

But I think great coverage can be achieved by this approach, and that it will result in tests that are easy to understand for RDF heads, at least, and I think that has some legitimacy.

**Comment by ericprud** [comment]
+1 to templating and parameterization
In ShEx, we maintain two versions of the manifest, [`.ttl`](https://github.com/shexSpec/shexTest/blob/master/validation/manifest.ttl) and [`.jsonld`](https://github.com/shexSpec/shexTest/blob/master/validation/manifest.jsonld). Because we have a [ttl-to-jsonld](https://github.com/shexSpec/shexTest/blob/master/bin/genJSON.js) converter, the `.ttl` manifests are implicitly authoritative; plus they can have comments.
This approach is a little less -eat-your-own-dogfood-y than making everyone use the `ttl`, but seems to make a lot of folks happy.
